# Generated by Django 5.2.17 on 2026-09-06 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0002_alter_chore_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('position', models.PositiveIntegerField(default=0)),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='chores.chore')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='ChoreDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='chores.chore')),
                ('depends_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='chores.chore')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('chore', 'depends_on'), name='unique_chore_dependency'), models.CheckConstraint(condition=models.Q(('chore', models.F('depends_on')), _negated=True), name='chore_cannot_depend_on_itself')],
            },
        ),
    ]
