# Generated by Django 5.2.17 on 2026-09-06 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0003_checklistitem_choredependency'),
        ('households', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoreOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('window_label', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('CLAIMED', 'Claimed'), ('DONE', 'Done'), ('OVERDUE', 'Overdue')], default='AVAILABLE', max_length=10)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('chore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='chores.chore')),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_occurrences', to='households.membership')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_occurrences', to='households.membership')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('chore', 'period_start'), name='unique_chore_period')],
            },
        ),
    ]
