# Generated by Django 5.2.17 on 2026-09-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0004_choreoccurrence'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoreTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category_name', models.CharField(max_length=100)),
                ('default_difficulty', models.PositiveSmallIntegerField(default=1)),
                ('default_minutes', models.PositiveIntegerField()),
                ('default_points', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
