# Generated by Django 5.2.17 on 2026-09-06 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0007_contribution'),
        ('households', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choreoccurrence',
            name='parent_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='choreoccurrence',
            name='parent_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_occurrences', to='households.membership'),
        ),
    ]
