# Generated by Django 5.2.17 on 2026-09-06 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0008_choreoccurrence_parent_confirmed_at_and_more'),
        ('households', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('COMPLETION', 'Completion'), ('ON_TIME', 'On time'), ('DIFFICULTY', 'Difficulty'), ('HELPING_OTHERS', 'Helping others')], max_length=20)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_awards', to='households.membership')),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_awards', to='chores.choreoccurrence')),
            ],
        ),
    ]
