# Generated by Django 5.2.17 on 2026-09-06 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0009_pointaward'),
        ('households', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FairnessSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of_date', models.DateField()),
                ('rolling_minutes', models.PositiveIntegerField()),
                ('availability_minutes', models.PositiveIntegerField()),
                ('fairness_pct', models.FloatField(blank=True, null=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fairness_snapshots', to='households.household')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fairness_snapshots', to='households.membership')),
            ],
            options={
                'ordering': ['as_of_date'],
                'constraints': [models.UniqueConstraint(fields=('household', 'member', 'as_of_date'), name='unique_fairness_snapshot_per_day')],
            },
        ),
    ]
