# Generated by Django 5.2.17 on 2026-09-06 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0010_fairnesssnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='choreoccurrence',
            name='photo_proof',
            field=models.ImageField(blank=True, null=True, upload_to='photo_proof/%Y/%m/'),
        ),
    ]
