# Generated by Django 5.2.17 on 2026-09-06 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0010_fairnesssnapshot'),
        ('households', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('chore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pauses', to='chores.chore')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pauses', to='households.membership')),
            ],
        ),
    ]
